<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Deprec_model extends CI_Model
{

    public $table = 'depreciation';
    public $id = 'no_deprec';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('no_deprec', $q);
        $this->db->or_like('no_label', $q);
	    $this->db->or_like('year_procurement', $q);
        $this->db->or_like('economics_age', $q);
        $this->db->or_like('acquisition_cost', $q);
        $this->db->or_like('dep_per_year', $q);
        $this->db->or_like('remaining_age', $q);
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('no_deprec', $q);
        $this->db->or_like('no_label', $q);
	    $this->db->or_like('year_procurement', $q);
        $this->db->or_like('economics_age', $q);
        $this->db->or_like('acquisition_cost', $q);
        $this->db->or_like('dep_per_year', $q);
        $this->db->or_like('remaining_age', $q);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function get_label($id) {
        $this->db->where('no_label', $id);
        $row = $this->db->get('label')->row(0);
        return $row;
    }

    public function rupiah($number){
        $format = "Rp ".number_format($number,0,',','.');
        return $format;
    }

    public function delete_rupiah($number){
        $format = preg_replace('/[Rp ]/','',$number);
        return $format;
    }

}

/* End of file pengaduan_model.php */
/* Location: ./application/models/pengaduan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-03 15:15:51 */
/* http://harviacode.com */