<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Room_model extends CI_Model
{

    public $table = 'room';
    public $id = 'id_room';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_room', $q);
	$this->db->or_like('name_room', $q);
    $this->db->or_like('location', $q);
	$this->db->or_like('pic', $q);
	$this->db->or_like('kind', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_room', $q);
	$this->db->or_like('name_room', $q);
    $this->db->or_like('location', $q);
	$this->db->or_like('pic', $q);
	$this->db->or_like('kind', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function get_kind($id) {
        $this->db->where('id_kind', $id);
        $row = $this->db->get('room_kind')->row(0);
        return $row;
    }

    public function get_user($id) {
        $this->db->where('niy', $id);
        $row = $this->db->get('users')->row(0);
        return $row;
    }

}

/* End of file pengaduan_model.php */
/* Location: ./application/models/pengaduan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-03 15:15:51 */
/* http://harviacode.com */