<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Room_clean_model extends CI_Model
{

    public $table = 'qc_room_clean';
    public $id = 'qc_rclean';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('qc_rclean', $q);
	    $this->db->or_like('room', $q);
        $this->db->or_like('instrument', $q);
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('qc_rclean', $q);
	    $this->db->or_like('room', $q);
        $this->db->or_like('instrument', $q);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function list_poin($id)
    {
        $this->db->select('*');
        $this->db->from($this->table);
        $this->db->join('room', 'room.id_room = qc_room_clean.room', 'left outer');
        $this->db->where('qc_room_clean.room', $id);
        return $this->db->get()->result();
    }

    public function get_room($id)
    {
        $this->db->where('id_room', $id);
        $row = $this->db->get('room')->row(0);
        return $row;
    }

    public function get_instrument($id)
    {
        $this->db->where('id_clean', $id);
        $row = $this->db->get('clean_instrument')->row(0);
        return $row;
    }

}

/* End of file pengaduan_model.php */
/* Location: ./application/models/pengaduan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-03 15:15:51 */
/* http://harviacode.com */